---
sonarr:
  image:
    repository: ghcr.io/linuxserver/sonarr
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: 4.0.14
  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: ""
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"
    hosts:
      - host: sonarr.theater.kelbert.fr
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 80
    tls:
      - secretName: sonarr-theater-kelbert-fr-tls
        hosts:
          - sonarr.theater.kelbert.fr

  resources: {}
    #TODO set proper resource limits

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    existingClaim: config

    # if you need any additional volumes, you can define them here
    additionalVolumes:
      - name: media
        persistentVolumeClaim:
          claimName: media

    # if you need any additional volume mounts, you can define them here
    additionalMounts:
      - name: media
        mountPath: /media
