---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-{{ .Release.Name }}"
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/volumes/media
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .Release.Name }}-media"
