---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1T
  volumeName: "media-{{ .Release.Name }}"
  storageClassName: "{{ .Release.Name }}-media"
