include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - maintenance

sast:
  stage: test

renovate:
  stage: maintenance
  image: renovate/renovate
  script:
    - echo "Repository path:" && pwd && ls -la
    - echo "Looking for renovate config..." && ls -la renovate.json || echo "renovate.json not found"
    - renovate $CI_PROJECT_PATH
  variables:
    RENOVATE_TOKEN: "$RENOVATE_TOKEN"
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_ENDPOINT: "https://gitlab.com/api/v4"
    LOG_LEVEL: "debug"
  only:
    - schedules
