include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - test
  - maintenance

sast:
  stage: test

renovate:
  stage: maintenance
  image: renovate/renovate
  script:
    - renovate --gitlab-project "$CI_PROJECT_PATH" --autodiscover=false
  variables:
    RENOVATE_TOKEN: "$RENOVATE_TOKEN"
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_ENDPOINT: "https://gitlab.com/api/v4"
    LOG_LEVEL: "debug"
  only:
    - schedules
