---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cocovoit
data:
  db_name: "cocovoit"
  db_host: "mout-ch-pg-cluster-1.postgres-op.svc.cluster.local"
  db_port: "5432"

  mail_host: "smtp.ionos.fr"
  mail_port: "587"
  mail_encryption: "tls"
  mail_sender_address: "no-reply@cocovoit.lab.kelbert.fr"

  app_env: "prod"
