---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
subsets:
  - addresses:
      # Get unique endpoint IPs from the first service
      {{- range .Values.services.vault.endpoints }}
      - ip: {{ .ip }}
      {{- end }}
    ports:
    {{- range $key, $service := .Values.services }}
      - name: {{ $service.name }}
        port: {{ $service.port }}
    {{- end }}
