{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  {{- range $key, $service := .Values.services }}
  - host: {{ $service.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $service.name }}-svc
              port:
                number: {{ $service.port }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- range $key, $service := .Values.services }}
    - hosts:
        - {{ $service.host }}
      secretName: {{ $service.host }}-tls
    {{- end }}
  {{- end }}
{{- end }}
