---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  {{- range $key, $service := .Values.services }}
  - name: {{ $service.name }}
    protocol: TCP
    port: {{ $service.port }}
    targetPort: {{ $service.name }}
  {{- end }}
  selector:
    app: {{ .Values.appName }}
