{{- range $key, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}-svc
  labels:
    app: {{ $.Values.appName }}
    service: {{ $service.name }}
spec:
  type: ClusterIP
  ports:
  - name: {{ $service.name }}
    protocol: TCP
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  {{- if $service.externalIPs }}
  externalIPs:
  {{- range $service.externalIPs }}
  - {{ . }}
  {{- end }}
  {{- end }}
  # No selector - this makes it a headless service that we can control endpoints for
{{- end }}
