---
ceph-csi-rbd:
  csiConfig:
    - clusterID: af88c536-4b0e-11ee-ad59-67497ccf2e7a
      monitors:
        - "192.168.14.10:6789"
        - "192.168.14.11:6789"
        - "192.168.14.12:6789"

  provisioner:
    replicaCount: 1

  storageClass:
    create: true
    clusterID: af88c536-4b0e-11ee-ad59-67497ccf2e7a
    pool: k3s
    mountOptions:
      - discard
