---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: simone-app
spec:
  path: apps/simone/app
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: simone-registry
spec:
  type: kubernetes.io/dockerconfigjson
  path: apps/simone/registry
  keys:
    - host
    - username
    - password
  templates:
    ".dockerconfigjson": |
      {
          "auths": {
              "{% .Secrets.host %}":{
                  "username":"{% .Secrets.username %}",
                  "password":"{% .Secrets.password %}",
                  "auth":"{% list .Secrets.username ":" .Secrets.password | join "" | b64enc %}"
        	    }
          }
      }
