---
authentik:
  authentik:
    secret_key: file:///goauthentik-creds/secret_key
    postgresql:
      host: mout-ch-pg-cluster-1.postgres-op.svc.cluster.local
      user: file:///postgres-creds/username
      password: file:///postgres-creds/password
    redis:
      enabled: true
  server:
    volumes:
      - name: postgres-creds
        secret:
          secretName: goauthentik.goauthentik.mout-ch-pg-cluster-1.credentials.postgresql.acid.zalan.do
      - name: goauthentik-creds
        secret:
          secretName: goauthentik-creds
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
      - name: goauthentik-creds
        mountPath: /goauthentik-creds
        readOnly: true
  worker:
    volumes:
      - name: postgres-creds
        secret:
          secretName: goauthentik.goauthentik.mout-ch-pg-cluster-1.credentials.postgresql.acid.zalan.do
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
