---
authentik:
  global:
    image:
      tag: 2023.10.7 # Latest contain a bug in db migration
  authentik:
    secret_key: file:///goauthentik-creds/secret_key
    postgresql:
      host: mout-ch-pg-cluster-1.postgres-op.svc.cluster.local
      name: goauthentik
      user: file:///postgres-creds/username
      password: file:///postgres-creds/password
  redis:
    enabled: true
  server:
    volumes:
      - name: postgres-creds
        secret:
          secretName: goauthentik.goauthentik.mout-ch-pg-cluster-1.credentials.postgresql.acid.zalan.do
      - name: goauthentik-creds
        secret:
          secretName: goauthentik-creds
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
      - name: goauthentik-creds
        mountPath: /goauthentik-creds
        readOnly: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      https: true
      hosts:
        - auth.kelbert.fr
      tls:
        - hosts:
          - auth.kelbert.fr
          secretName: auth.kelbert.fr-tls

  worker:
    volumes:
      - name: postgres-creds
        secret:
          secretName: goauthentik.goauthentik.mout-ch-pg-cluster-1.credentials.postgresql.acid.zalan.do
    volumeMounts:
      - name: postgres-creds
        mountPath: /postgres-creds
        readOnly: true
