---
authentik:
  secret_key: woksjhudvnjslaie
  postgresql:
    host: mout-ch-pg-cluster-1.postgres-op.svc.cluster.local
    name: goauthentik
    user: goauthentik.goauthentik
    password: passw0rd
  redis:
    enabled: true
