---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-theater-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: theater-1.magstatt
    namespace: cert-manager
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: apps/cert-manager-theater-1
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
