---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epibank
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: epibank
  project: default
  source:
    path: apps/epibank
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
