---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: apps/firefly
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD