---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: theater-1.magstatt
    namespace: jackett
  project: default
  syncPolicy: {}
  source:
    chart: jackett
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 11.7.2
    helm:
      valuesObject:
        image:
          repository: ghcr.io/hotio/jackett
          tag: release-0.22.1971
        persistence:
          config:
            enabled: true
            size: 1Gi
            storageClass: local-path

        ingress:
          main:
            enabled: true
            className: ""
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
              traefik.ingress.kubernetes.io/frontend-entry-points: http,https
              traefik.ingress.kubernetes.io/redirect-entry-point: https
              traefik.ingress.kubernetes.io/redirect-permanent: "true"
            hosts:
              - host: jackett.theater.kelbert.fr
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: jackett
                        port:
                          number: 9117
            tls:
              - secretName: jackett-theater-kelbert-fr-tls
                hosts:
                  - jackett.theater.kelbert.fr
