---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: theater-1.magstatt
    namespace: jackett
  project: default
  syncPolicy: {}
  source:
    chart: jackett
    repoURL: https://k8s-at-home.com/charts/
    targetRevision: 11.7.2
    helm:
      valuesObject:
        image:
          repository: linuxserver/jackett
          tag: 0.22.474
        persistence:
          config:
            enabled: true
            size: 1Gi
            storageClass: local-path

        ingress:
          main:
            enabled: true
            className: ""
            annotations: { }
            # kubernetes.io/ingress.class: nginx
            # kubernetes.io/tls-acme: "true"
            hosts:
              - host: jackett.theater.kelbert.fr
                paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: jackett
                        port:
                          number: 9117
