---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: theater-1.magstatt
    namespace: jellyfin
  project: default
  source:
    path: apps/jellyfin
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
  syncPolicy: {}
