---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft-2
  project: default
  source:
    path: apps/minecraft-2
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
  syncPolicy: {}
