---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pharmacie-blotzheim
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: pharmacie-blotzheim
  project: default
  source:
    path: apps/pharmacie-blotzheim
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
