---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-op
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-op
  project: default
  source:
    path: apps/postgres-op
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: 2-add-postgres-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
