---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simone
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: simone
  project: default
  source:
    path: apps/simone
    repoURL: https://gitlab.com/mout.ch/k8s.git
    targetRevision: HEAD
  syncPolicy: {}
