

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: storj-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  type: Opaque
  path: apps/storj/repo
  keys:
    - username
    - password
  templates:
    password: "{% .Secrets.password %}"
    project: storj
    type: git
    url: "https://gitlab.com/rootmout/storj.git"
    username: "{% .Secrets.username %}"
