---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://gitlab.com/rootmout/storj.git
        revision: HEAD
        files:
        - path: "nodes/*"
  syncPolicy: {}
  template:
    metadata:
      name: {{ printf "'storj-{{.path.filename}}'" }}
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: storj
      project: storj
      sources:
        - path: charts/storj-storagenode
          repoURL: https://github.com/rootmout/storj-storagenode-chart
          targetRevision: HEAD
          helm:
            valuesObject:
              fullnameOverride: {{ printf "'storj-{{.path.filename}}'" }}
              metrics:
                enabled: false
              config:
                wallet: 0x6F0F29eE3932C20739B9e1c1368eaBAB5EB9117B
                email: pierre.kelbert+storj@gmail.com
                address: {{ printf "'{{.ip}}:28967'" }}
                storage: 2Ti
              identity:
                vaultSecret:
                  spec:
                    path: {{ printf "'apps/storj/nodes/{{.path.filename}}'" }}
                    type: Opaque
              serviceAccount:
                create: true
                name: {{ printf "'{{.path.filename}}'" }}
              persistence:
                enabled: true
                annotations: {}
                volumeClaimTemplate:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: {{ printf "'{{.size}}'" }}
                  storageClassName: {{ printf "'{{.storage_class}}'" }}

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: storj-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  type: Opaque
  path: apps/storj/repo
  keys:
    - username
    - password
  templates:
    password: "{% .Secrets.password %}"
    project: storj
    type: git
    url: "https://gitlab.com/rootmout/storj.git"
    username: "{% .Secrets.username %}"
