---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://gitlab.com/rootmout/storj.git
        revision: HEAD
        files:
        - path: "nodes/*"
  syncPolicy: {}
  template:
    metadata:
      name: {{ printf "'{{.path.filename}}-storj'" }}
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: storj
      project: storj
      source:
        path: apps/storj
        repoURL: https://gitlab.com/mout.ch/k8s.git
        targetRevision: HEAD


---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: storj-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  type: Opaque
  path: apps/storj/repo
  keys:
    - username
    - password
  templates:
    password: "{% .Secrets.password %}"
    project: storj
    type: git
    url: "https://gitlab.com/rootmout/storj.git"
    username: "{% .Secrets.username %}"
