---
rabbitmq:
  auth:
    username: rabbitmq
    existingPasswordSecret: rabbitmq-auth
    existingPasswordKey: password
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
