apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  destination:
    name: ''
    namespace: consul
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.40.0
    chart: consul
    helm:
      valueFiles:
        - values.yaml
  project: default
