---
owncloud:
  global:
    storageClass: csi-rbd-sc
  owncloudHost: cloud.kelbert.fr
  persistence:
    size: 50Gi

  service:
    type: ClusterIP

  ingress:
    enabled: true
    tls: true
    certManager: true
    hostname: cloud.kelbert.fr
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/frontend-entry-points: http,https
      traefik.ingress.kubernetes.io/redirect-entry-point: https
      traefik.ingress.kubernetes.io/redirect-permanent: "true"

  tls: true
