---
zigbee2mqtt:
  # Koenkk/zigbee2mqtt-chart configuration
  image:
    repository: koenkk/zigbee2mqtt
    tag: "1.35.1"
    pullPolicy: IfNotPresent

  env:
    TZ: "Europe/Zurich"

  statefulset:
    secrets:
      name: mqtt-account
    storage:
      enabled: false

  service:
    type: ClusterIP
    port: 8080

    # Ingress configuration
  # ingress:
  #   enabled: true
  #   className: traefik
  #   annotations:
  #     cert-manager.io/cluster-issuer: letsencrypt-prod
  #     traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
  #     traefik.ingress.kubernetes.io/frontend-entry-points: http,https
  #     traefik.ingress.kubernetes.io/redirect-entry-point: https
  #     traefik.ingress.kubernetes.io/redirect-permanent: "true"
  #   hosts:
  #     - host: zigbee2mqtt.theater.kelbert.fr
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #   tls:
  #     - hosts:
  #         - zigbee2mqtt.theater.kelbert.fr
  #       secretName: zigbee2mqtt-theater-kelbert-fr-tls

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Node selection
  nodeSelector: {}
  tolerations: []
  affinity: {}

  zigbee2mqtt:
    advanced:
      channel: 11
      elapsed: true
      homeassistant_discovery_topic: homeassistant
      homeassistant_status_topic: homeassistant/status
      last_seen: ISO_8601
      log_level: info
      log_output:
      - console
      network_key: GENERATE
      pan_id: 6754
      transmit_power: 20
    device_options:
      retain: false
    experimental:
      new_api: true
    frontend:
      host: 0.0.0.0
      port: 8080
    homeassistant: true
    mqtt:
      base_topic: zigbee2mqtt
      include_device_information: true
      password: '!secret.yaml password'
      server: mqtt://mosquitto.mosquitto.svc.cluster.local:1883
      user: '!secret.yaml user'
    permit_join: true
    serial:
      adapter: zstack
      baudrate: 115200
      disable_led: false
      port: tcp://192.168.1.216:6638