---
mosquitto:
  service:
    type: NodePort
    ports:
      mqtt: 1883
      mqttssl: 8883
      mqttws: 9001

  mosquitto:
    config: |
      allow_anonymous false
      log_dest stdout
      log_type all

    existingSecretUsers: mosquitto-auth

    acls: |
      user theater-switch
      topic readwrite #
