---
apiVersion: v2
name: postgres-op
description: zalendo postgres operator

type: application
version: 0.1.0

dependencies:
  - name: postgres-operator
    version: 1.14.0
    repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
