argo-cd:
  global:
    domain: argocd.infra.mout.ch
  configs:
    params:
      server.insecure: "true"
  dex:
    enabled: false
  server:
    # Removed --insecure flag for proper HTTPS support
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
    ingress:
      enabled: true
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      hosts:
        - argocd.infra.mout.ch
      tls:
        - hosts:
          - argocd.infra.mout.ch
          secretName: argocd.infra.mout.ch-tls
