apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-public-proxy-config
  namespace: immich
data:
  config.json: |
    {
      "ipp": {
        "allowDownloadAll": 2,
        "showMetadata": {
          "description": {
            "caption": true,
            "sidebar": true
          },
          "exif": {
            "dateTimeOriginal": true,
            "timeZone": false,
            "fileName": false,
            "dimensions": true,
            "fileSize": true,
            "make": true,
            "model": true,
            "lensModel": true,
            "exposureTime": true,
            "iso": true,
            "fNumber": true,
            "focalLength": true
          },
          "location": {
            "city": false,
            "state": false,
            "country": false,
            "gps": false
          }
        },
        "gallery": {
          "showTitle": true,
          "showDescription": true
        },
        "lightbox": {
          "showDownload": true
        }
      }
    }
