apiVersion: v2
name: jellyseerr
description: A Helm chart for Jellyseerr
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: jellyseerr
    version: 2.4.0
    repository: oci://tccr.io/truecharts
