---
jellyseerr-chart:
  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              TZ: "Europe/Zurich"
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi

  service:
    main:
      ports:
        main:
          port: 5055
          protocol: http

  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      hosts:
        - host: jellyseerr.theater.kelbert.fr
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 5055
      tls:
        - secretName: jellyseerr-theater-kelbert-fr-tls
          hosts:
            - jellyseerr.theater.kelbert.fr

  persistence:
    config:
      enabled: true
      type: pvc
      storageClass: local-path
      size: 1Gi
      retain: true
