---
  grafana:
    grafana.ini:
      panels:
        enable_alpha: true
        disable_sanitize_html: true
      security:
        allow_embedding: true
        cookie_samesite: none
        cookie_secure: true # Can be enabled when behind a TLS proxy
    datasources:
      datasources.yaml:
       apiVersion: 1
       datasources:
       - name: Prometheus
         type: prometheus
         url: http://prometheus-server.prometheus.svc.cluster.local
         access: proxy
         isDefault: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
      hosts:
        - grafana.infra.mout.ch
      tls:
        - hosts:
          - grafana.infra.mout.ch
          secretName: grafana.infra.mout.ch-tls
    admin:
      existingSecret: "grafana"
      userKey: "username"
      passwordKey: "password"
    dashboards:
      default:
        ceph:
          gnetId: 2842
          revision: 17
          datasource: Prometheus
        traefik:
          gnetId: 4475
          revision: 5
          datasource: Prometheus
        node-exporter:
          gnetId: 1860
          revision: 36
          datasource: Prometheus
        cert-manager:
          gnetId: 11001
          revision: 1
          datasource: Prometheus
        nextcloud:
          gnetId: 9632
          revision: 1
          datasource: Prometheus
        k3s:
          gnetId: 15282
          revision: 1
          datasource: Prometheus
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
