---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mout-ch-pg-cluster-1
  namespace: postgres-op
spec:
  teamId: "mout-ch"
  volume:
    size: 70Gi
    storageClass: csi-rbd-sc
  numberOfInstances: 2
  users:
    rootmout:
    - superuser
    - createdb
    # prefixed with owncloud. to make secret available on owncloud namespace
    nextcloud.nextcloud: []
    cocovoit.cocovoit: []
    epibank.epibank: []
    simone.simone: []
    goauthentik.goauthentik: []
    firefly.firefly: []
  databases:
    nextcloud: nextcloud.nextcloud
    cocovoit: cocovoit.cocovoit
    epibank: epibank.epibank
    simone: simone.simone
    goauthentik: goauthentik.goauthentik
    firefly: firefly.firefly
  postgresql:
    version: "14"
