---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: mout-ch-pg-cluster-1
  namespace: postgres-op
spec:
  teamId: "mout-ch"
  volume:
    size: 1Gi
    storageClass: csi-rbd-sc
  numberOfInstances: 2
  users:
    rootmout:  # database owner
    - superuser
    - createdb
    owncloud.owncloud-db: []  # role for application foo
  databases:
    owncloud-db: owncloud.owncloud-db  # dbname: owner
  postgresql:
    version: "14"
