---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: mosquitto-auth
spec:
  path: apps/mosquitto/auth
  type: Opaque
  templates:
    users: |
      {{- range $key, $value := .Secrets.users }}
        {{ $key }}:{{ $value }}
      {{- end }}
