---
consul:
  global:
    image: hashicorp/consul:1.11.2
    datacenter: dc2
    federation:
      enabled: true
      primaryDatacenter: "dc1"
      primaryGateways: [ 192.168.11.10:8555 ]

    tls:
      enabled: true
      caCert:
        secretName: consul-federation
        secretKey: caCert
      caKey:
        secretName: consul-federation
        secretKey: caKey

    acls:
      manageSystemACLs: true
      replicationToken:
        secretName: consul-federation
        secretKey: replicationToken

    gossipEncryption:
      secretName: consul-federation
      secretKey: gossipEncryptionKey

  controller:
    enabled: true

  meshGateway:
    enabled: true
    replicas: 1
    service:
      nodePort: 8555
      enabled: true
      type: NodePort
    wanAddress:
      enabled: true
      source: "Static"
      static: "compute-1.hirsingue.infra.mout.ch"
      port: 8555

  connectInject:
    enabled: true

  server:
    replicas: 1
