---
minecraft:
  image:
    repository: itzg/minecraft-server
    tag: 2022.16.0-java17
    pullPolicy: IfNotPresent
    pullSecret: ""

  resources:
    requests:
      memory: 4096Mi
      cpu: 500m

  livenessProbe:
    initialDelaySeconds: 900

  extraEnv:
    GENERIC_PACK: https://mediafilez.forgecdn.net/files/4749/383/Server-Files-1.0.27.zip
    USE_MODPACK_START_SCRIPT: false
    MAX_MEMORY: 8G

  minecraftServer:
    type: FORGE
    eula: "TRUE"
    version: "1.19.2"
    forgeVersion: "43.2.23"
    memory: 4096M
    motd: "Benjito <3"
    serviceType: NodePort
    nodePort: 30573
    removeOldMods: true
    onlineMode: default
    rcon:
      enabled: true
      existingSecret: minecraft-rcon
      secretKey: password
    extraPorts:
      - name: metrics
        containerPort: 9150
        protocol: TCP
        service:
          enabled: true
          embedded: false
          annotations:
            prometheus.io/port: '9150'
            prometheus.io/scrape: 'true'
          type: ClusterIP
          port: 9150
        ingress:
          enabled: false

  sidecarContainers:
    - name: exporter
      image: ghcr.io/dirien/minecraft-exporter:0.17.1
      volumeMounts:
        - mountPath: /minecraft/world
          name: datadir
          subPath: world
          readOnly: true
      env:
        - name: MC_RCON_ADDRESS
          value: '127.0.0.1:25575'
        - name: MC_RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: minecraft-rcon
        - name: WEB_DISABLED_EXPORTER_METRICS
          value: 'true'
        - name: MC_MOD_SERVER_STATS
          value: 'forge'

  persistence:
    storageClass: csi-rbd-sc
    dataDir:
      enabled: true
      Size: 10Gi
