---
minecraft:
  image:
    repository: itzg/minecraft-server
    tag: 2022.16.0-java17
    pullPolicy: IfNotPresent
    pullSecret: ""

  minecraftServer:
    eula: "TRUE"
    motd: "Welcome to minecraft.mout.ch server!"
    serviceType: NodePort
    NodePort: 25565

  persistence:
    storageClass: csi-rbd-sc
    enabled: true
    Size: 1Gi
