---
minecraft:
  image:
    repository: itzg/minecraft-server
    tag: 2022.16.0-java17
    pullPolicy: IfNotPresent
    pullSecret: ""

  minecraftServer:
    eula: "TRUE"
    motd: "Welcome to minecraft.mout.ch server!"
  persistence:
    storageClass: csi-rbd-sc
